spring.application.name=panga-api

server.port=${PORT:8080}

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/bankapi}
spring.datasource.username=${DATABASE_USER:bankuser}
spring.datasource.password=${DATABASE_PASSWORD:bankpass}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

springdoc.swagger-ui.path=/swagger-ui.html